
name: Build app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STORE_BASE64: ${{ secrets.SIGNING_STORE_BASE64 }}
      STORE_PASS: ${{ secrets.SIGNING_STORE_PASSWORD }}
      KEY_NAME: ${{ secrets.SIGNING_KEY_ALIAS }}
      KEY_PASS: ${{ secrets.SIGNING_KEY_PASSWORD }}
      STORE_NAME: "keystore.jks"

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo $STORE_BASE64 > keystore.txt
          base64 -d keystore.txt > $STORE_NAME
          
      - name: Grant permission
        run: chmod -R 777 ./gradlew

      - name: Build APK
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/$STORE_NAME \
          -Pandroid.injected.signing.store.password=$STORE_PASS \
          -Pandroid.injected.signing.key.alias=$KEY_NAME \
          -Pandroid.injected.signing.key.password=$KEY_PASS

      - name: Build AAB
        run: |
          ./gradlew bundleRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/$STORE_NAME \
          -Pandroid.injected.signing.store.password=$STORE_PASS \
          -Pandroid.injected.signing.key.alias=$KEY_NAME \
          -Pandroid.injected.signing.key.password=$KEY_PASS

      - uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            android/build/outputs/apk/release/
            android/build/outputs/bundle/release/
